### ISSUE TITLE
Can i use the FFS method in SSAGES to compute the nucleation rate?

### ISSUE THREAD

**Issue by sxd-1990** [SSAGESproject/SSAGES#17]
Dear SSAGES Developers,

My reasearch direction is the nucleation and crystallization of Lennard-Jones potential systems. Where i am interested in SSAGES is the FFS method which is often used in literatures together with Monte Carlo simulation to comupute the nucleation rate. But in SSAGES the dynamics engine is MD. In this case , could i use it to compute the nuclation rate ?
                                                                               
Best wishes,
Xiaodong Su

**Comment by jonathankwhitmer** [comment]
@sxd-1990: A hook would have to be written for SSAGES to link to your MC code; this is in principle possible, and some idea about what information is needed to link to the code is in the "hooks" source directory. We do not have documentation outlining generic hooks at this time, but will address this in a future release.

**Comment by sxd-1990** [comment]
Hi,

Thank you very much for your reply.  Another question i want to ask is, can i calculate the nucleation rate only by combining FFS and the MD-engine, not MC-engine. 
                                                                               
Best wishes,
Xiaodong Su

**Comment by mquevill** [comment]
1. In theory, yes, you could use FFS and an MD engine to calculate the nucleation rate. However, you would need a good CV for that system and be able to define interfaces for FFS.
2. The collective variables in LAMMPS or PLUMED cannot be used in SSAGES. Since some methods require the gradients of a CV, SSAGES needs to have both the value calculation and the gradient calculation. There are many CVs that are simple to calculate, but their gradient is much more complicated to calculate. As long as you can pass both the value _and its gradient_ to SSAGES, you could hook them together. Currently, we do not have plans for implementing this.
