### ISSUE TITLE
How can I carry out well-tempered Metadynamics using SSAGES?

### ISSUE THREAD

**Issue by wxsongsh** [SSAGESproject/SSAGES#29]
Dear SSAGES Developers,

From the website of SSAGES, I know that, currently, we cannot use the adaptive-gaussian biases in the metadynamics simulation. In order to calculate the free energy more accurate, it is better to implement the well-tempered or adaptive gaussians metadynamics, where the hills should be lower as the wells in the free energy landscape have been filled. What can I do for obtaining the accurate free energy?

A practical solution may be that I change the code by controling the height of the added hills using the following formula: 
      W = w_0*exp(-V(s)/V_max), 
where W is the current hill that depend on current bias potential V(s); V_max is the set maximum bias potential.

On the other hand, I find SSAGES has a new method named Artificial Neural Network, which also can obtain the free energy. I do not know its efficiency and accuracy, compared with metadynamics.

Thanks!

**Comment by mquevill** [comment]
Yes, there are many "flavors" of metadynamics that can be useful in certain circumstances. We currently only have the base version of metadynamics with a constant hill shape and size. We have a well-tempered version of metadynamics in development that is not yet ready for release.

There are several methods in SSAGES that are able to calculate the free energy. Some are quite standard (Metadynamics and Adaptive Biasing Force) and some are novel to SSAGES (Basis Function Sampling, Artificial Neural Network Sampling, and Combined Force-Frequency Sampling). Additionally, Umbrella Sampling can be paired with [WHAM](http://membrane.urmc.rochester.edu/?page_id=126) to get a free energy profile. There are quite a few examples of how to use these methods included in the repository (the `Examples/User` directory) so that you can adapt them to your system.

In regards to the comparison of the ANN method to metadynamics or other free energy methods, consult the paper (https://doi.org/10.1063/1.5018708) and the associated repository (https://github.com/hsidky/ann_sampling), which contains comparisons of ANN sampling to several free energy methods.

**Comment by wxsongsh** [comment]
Thanks.
